export { default as Account } from './Account/Account'
export { default as Bundles } from './Bundles/Bundles'
export { default as Cart } from './Cart/Cart'
export { default as Checkout } from './Checkout/Checkout'
export { default as Contact } from './Contact/Contact'
export { default as Home } from './Home/Home'
export { default as Login } from './Login/Login'
export { default as Signup } from './Signup/Signup'
export { default as ProductInfo } from './ProductInfo/ProductInfo'
export { default as Templates } from './Templates/Templates'
export { default as ThankYou } from './ThankYou/ThankYou'
export { default as PageNotFound } from './PageNotFound/PageNotFound'

// ADMIN PAGES
export { default as Customers } from './Admin/Customers/Customers'
export { default as Dashboard } from './Admin/Dashboard/Dashboard'
export { default as Products } from './Admin/Products/Products'
export { default as Orders } from './Admin/Orders/Orders'
